// 统一内容源：页面结构只保留一套，正文数据在这里同时维护中英文。
window.siteContent = {
  shared: {
    researchInterests: {
      en:
        "Large Language Models; Multimodal Large Language Models; Natural Language Processing; Generative Models; Diffusion Models; Computer Vision; Medical AI; Model Security and Robustness; Model Interpretability; mmWave Sensing; Sensors; Embedded Systems.",
      zh:
        "大语言模型；多模态大语言模型；自然语言处理；生成式模型；扩散模型；计算机视觉；医学人工智能；模型安全与鲁棒性；模型可解释性；毫米波感知；传感器；嵌入式系统。",
    },
    skills: {
      left: [
        {
          labelEn: "Programming Languages",
          labelZh: "编程语言",
          valueEn: "Python, C, C++, CUDA, MATLAB, SQL",
          valueZh: "Python、C、C++、CUDA、MATLAB、SQL",
        },
        {
          labelEn: "Frameworks",
          labelZh: "框架",
          valueEn:
            "PyTorch, TensorFlow, DeepSpeed, Transformers, Diffusers, LangChain, LangGraph, Pydantic-AI, FastAPI, Django",
          valueZh:
            "PyTorch、TensorFlow、DeepSpeed、Transformers、Diffusers、LangChain、LangGraph、Pydantic-AI、FastAPI、Django",
        },
        {
          labelEn: "Specialized Models",
          labelZh: "专长模型",
          valueEn:
            "LLM / MLLM, DiT / Stable Diffusion, CLIP / ViT / ResNet, YOLO, RetinaFace, Point Transformer, SimCLR, 3D VQGAN",
          valueZh:
            "LLM / MLLM、DiT / Stable Diffusion、CLIP / ViT / ResNet、YOLO、RetinaFace、Point Transformer、SimCLR、3D VQGAN",
        },
      ],
      right: [
        {
          labelEn: "Tools and Platforms",
          labelZh: "工具与平台",
          valueEn: "Docker, Vertex AI, Ollama / vLLM, FAISS, RAG systems, PostgreSQL, Git",
          valueZh: "Docker、Vertex AI、Ollama / vLLM、FAISS、RAG 系统、PostgreSQL、Git",
        },
        {
          labelEn: "Hardware",
          labelZh: "硬件",
          valueEn:
            "mmWave radar (TI IWR6843 / 1843, Cascade EVM), STM32, ESP8266 / ESP32, I2C / SPI / UART / RS-485 / Modbus, GPU / CUDA optimization",
          valueZh:
            "毫米波雷达（TI IWR6843 / 1843、Cascade EVM）、STM32、ESP8266 / ESP32、I2C / SPI / UART / RS-485 / Modbus、GPU / CUDA 优化",
        },
        {
          labelEn: "Libraries",
          labelZh: "库",
          valueEn: "NumPy, Pandas, Scikit-learn, XGBoost, AutoGluon, OpenCV, VTK, Mayavi",
          valueZh: "NumPy、Pandas、Scikit-learn、XGBoost、AutoGluon、OpenCV、VTK、Mayavi",
        },
      ],
    },
  },
  home: {
    focus: [
      {
        en: "LLM evaluation, reasoning, and post-training",
        zh: "LLM 评测、推理与后训练",
      },
      {
        en: "Multimodal and medical AI systems",
        zh: "多模态与医学 AI 系统",
      },
      {
        en: "Security and robustness for sensing and model pipelines",
        zh: "感知系统与模型流水线的安全性和鲁棒性",
      },
      {
        en: "From-scratch learning projects and systems implementation",
        zh: "从零实现型学习项目与系统工程实现",
      },
    ],
    highlights: [
      {
        en: "Improved BERT validation measurements from 10^-6 to 10^-12 at Xperf through automated optimization.",
        zh: "在 Xperf 通过自动化优化将 BERT 验证指标从 10^-6 提升到 10^-12。",
      },
      {
        en: "Built full-stack LLM and retrieval systems supporting 500+ queries per second during my Infraeo internship.",
        zh: "在 Infraeo 实习期间构建了支持 500+ QPS 的全栈 LLM 与检索系统。",
      },
      {
        en: "Published or contributed to work spanning ICDCS, ICCCN, Journal of Biomedical Informatics, BIO Integration, Computation, and multiple domain journals.",
        zh: "已发表或参与发表的工作覆盖 ICDCS、ICCCN、Journal of Biomedical Informatics、BIO Integration、Computation 等会议与期刊。",
      },
    ],
  },
  experience: {
    industry: [
      {
        titleEn: "Xperf (Internship)",
        titleZh: "Xperf（实习）",
        meta: "Sep 2025 - Dec 2025",
        roleEn: "AI Research and AI/ML Optimization Engineer",
        roleZh: "AI 研究与 AI/ML 优化工程师",
        bullets: [
          {
            en: "Developed a PSO-based closed-loop optimization framework for Marvell high-speed interconnect validation workflows, supporting AEC parameter tuning across 400G / 800G product-line setups and 1.6T simulator environments.",
            zh: "面向 Marvell 高速互连验证流程开发了基于 PSO 的闭环优化框架，支持 400G / 800G 产品线配置与 1.6T 仿真环境下的 AEC 参数调优。",
          },
          {
            en: "Improved BERT measurement results from 10^-6 to 10^-12 through automated multi-objective optimization, reducing manual engineering effort by 97%.",
            zh: "通过自动化多目标优化将 BERT 测试结果从 10^-6 提升到 10^-12，并将人工工程调参工作量降低了 97%。",
          },
          {
            en: "Designed and implemented a multiprocessing-based single-machine parallel framework for scalable PSO evaluation across multidimensional cable-configuration search spaces, using adaptive scheduling to reduce convergence time from hours to minutes.",
            zh: "设计并实现了基于多进程的单机并行框架，用于在多维线缆配置搜索空间中扩展 PSO 评估，通过自适应调度将收敛时间从数小时降到数分钟。",
          },
          {
            en: "Built an end-to-end automated validation pipeline with self-developed APIs to control BERT testing, parallel parameter tuning, and I2C EEPROM programming; worked with Marvell-chip-based OSFP-DD / QSFP AEC, optical transceiver modules, and cable ecosystems.",
            zh: "构建了端到端自动化验证流水线，通过自研 API 控制 BERT 测试、并行参数调优和 I2C EEPROM 烧录；涉及基于 Marvell 芯片的 OSFP-DD / QSFP AEC、光模块与线缆生态。",
          },
          {
            en: "Applied Mask R-CNN for optical inspection of failed solder joints in DAC-related validation workflows, supporting automated defect detection with BERT-based testing.",
            zh: "在 DAC 相关验证流程中使用 Mask R-CNN 对焊点失效进行光学检测，配合 BERT 测试实现自动化缺陷识别。",
          },
        ],
      },
      {
        titleEn: "Infraeo (Internship)",
        titleZh: "Infraeo（实习）",
        meta: "May 2025 - Dec 2025",
        roleEn: "Machine Learning and Deep Learning Engineer",
        roleZh: "机器学习与深度学习工程师",
        bullets: [
          {
            en: "Deployed and fine-tuned large language models up to 1000B parameters, including Qwen3 235B, Qwen3 Coder 480B, Kimi v2 1000B, Llama 3.3 70B, and GPT-OSS 120B, for domain-specific question answering with CoT prompting and RAG, reaching 89% answer accuracy.",
            zh: "部署并微调了最高 1000B 参数级别的大语言模型，包括 Qwen3 235B、Qwen3 Coder 480B、Kimi v2 1000B、Llama 3.3 70B 和 GPT-OSS 120B，用于结合 CoT 提示与 RAG 的领域问答，答案准确率达到 89%。",
          },
          {
            en: "Built semantic retrieval over 2M+ documents with FAISS-based embeddings that generated 768-dimensional vectors and a BERT reranker, achieving recall@10 of 0.94 and precision@5 of 0.87.",
            zh: "基于 FAISS 向量检索、768 维嵌入和 BERT 重排器构建了覆盖 200 万+ 文档的语义检索系统，达到 recall@10 为 0.94、precision@5 为 0.87。",
          },
          {
            en: "Fine-tuned Qwen and Llama models with LoRA and QLoRA using PyTorch, Unsloth, and Hugging Face Transformers, delivering 3.2x faster inference and 60% lower memory usage; developed full-stack AI services with FastAPI, Django, Docker, and Kubernetes supporting 500+ queries per second.",
            zh: "使用 PyTorch、Unsloth 和 Hugging Face Transformers，通过 LoRA 和 QLoRA 微调 Qwen 与 Llama 模型，实现 3.2 倍推理加速和 60% 显存降低；并用 FastAPI、Django、Docker、Kubernetes 开发了支持 500+ QPS 的全栈 AI 服务。",
          },
          {
            en: "Designed end-to-end machine learning pipelines processing 100GB+ of daily data, deployed to cloud environments, and integrated vector databases (FAISS, ElasticSearch), PostgreSQL, and LangChain / LangGraph for multi-agent workflows.",
            zh: "设计了端到端机器学习流水线，处理 100GB+ 的日数据量并部署到云环境，同时整合 FAISS、ElasticSearch、PostgreSQL 以及 LangChain / LangGraph 多智能体流程。",
          },
        ],
      },
      {
        titleEn: "Hanergy Mobile Energy Holding Group (Internship)",
        titleZh: "汉能移动能源控股集团（实习）",
        meta: "2019",
        roleEn: "R&D Hardware Engineer",
        roleZh: "研发硬件工程师",
        bullets: [
          {
            en: "Developed a smart wireless weather monitoring system integrating STM32, LCD2004, SPI OLED, air-pressure sensors, temperature and humidity modules, seven-segment displays, UART GPS, WiFi modules, and anemometer components.",
            zh: "开发了智能无线气象监测系统，集成 STM32、LCD2004、SPI OLED、气压传感器、温湿度模块、数码管、UART GPS、WiFi 模块和风速仪组件。",
          },
          {
            en: "Supported embedded hardware integration and system bring-up across sensing, communication, and display modules for field-oriented monitoring applications.",
            zh: "面向现场监测应用，完成了感知、通信与显示模块的嵌入式硬件集成与系统联调。",
          },
        ],
      },
      {
        titleEn: "Beijing University of Technology",
        titleZh: "北京工业大学",
        meta: "Sep 2017 - May 2019",
        roleEn: "R&D Assistant",
        roleZh: "研发助理",
        bullets: [
          {
            en: "Developed a six-degree-of-freedom robotic arm control system using STM32, stepper motors, sensors, cameras, and a custom four-layer PCB.",
            zh: "使用 STM32、步进电机、传感器、摄像头和自制四层 PCB 开发了六自由度机械臂控制系统。",
          },
          {
            en: "Built and configured an 8-node compute cluster with Intel Xeon E5-2696 v3 CPUs, NVIDIA Tesla K80 GPUs, RAID 50 storage, and VPN / SSH-enabled remote access.",
            zh: "搭建并配置了 8 节点计算集群，包含 Intel Xeon E5-2696 v3、NVIDIA Tesla K80、RAID 50 存储，以及支持 VPN / SSH 的远程访问环境。",
          },
        ],
      },
    ],
    research: [
      {
        titleEn: "Indiana University School of Medicine",
        titleZh: "印第安纳大学医学院",
        meta: "Nov 2020 - Aug 2021; Aug 2025 - May 2026",
        roleEn: "Research Assistant",
        roleZh: "研究助理",
        bullets: [
          {
            en: "Developed a two-stage generative framework combining 3D VQGAN with latent Diffusion Transformer (DiT) to synthesize volumetric sMRI scans for Alzheimer's research, leveraging DeepSpeed for distributed training.",
            zh: "开发了结合 3D VQGAN 与 latent Diffusion Transformer（DiT）的两阶段生成框架，用于合成阿尔茨海默病研究中的体积 sMRI 扫描，并使用 DeepSpeed 进行分布式训练。",
          },
          {
            en: "Implemented a self-supervised Point Transformer pipeline for 4096-point facial point clouds with SimCLR-based contrastive learning for forensic anthropometry, producing pose- and scale-robust geometric representations.",
            zh: "为 4096 点人脸点云实现了自监督 Point Transformer 流水线，结合基于 SimCLR 的对比学习服务于法医人类测量学，得到对姿态与尺度更稳健的几何表示。",
          },
          {
            en: "Contributed to DeepChrInteract, a Python deep learning toolkit for genome-wide chromatin interaction prediction, and conducted DNA / RNA analysis, enhancer-promoter prediction, and chromatin interaction prediction using 1D-CNN, 2D-CNN, LSTM, BLSTM, FCNN, flat VGG-like networks, ResNet, DenseNet, Random Forest, and SVM models.",
            zh: "参与开发了用于全基因组染色质互作预测的 Python 深度学习工具包 DeepChrInteract，并使用 1D-CNN、2D-CNN、LSTM、BLSTM、FCNN、平坦化 VGG 风格网络、ResNet、DenseNet、随机森林和 SVM 进行 DNA / RNA 分析、增强子-启动子预测与染色质互作预测。",
          },
          {
            en: "Reproduced and extended DeepChrInteract for enhancer-promoter interaction prediction, supporting one-hot, k-mer, and DNA-LLM inputs.",
            zh: "复现并扩展了 DeepChrInteract，用于增强子-启动子互作预测，支持 one-hot、k-mer 和 DNA-LLM 输入。",
          },
          {
            en: "Systematically evaluated 14 encoder architectures, including CNN, BiLSTM, mLSTM, xLSTM, Transformer, Linear Transformer, iTransformer, Mamba, RWKV, MAE, and DNA LLMs such as DNABERT, DNABERT-2, NT, and HyenaDNA; designed 6 fusion strategies including concatenation, addition, subtraction, element-wise multiplication, bilinear fusion, and concatenation-difference-product fusion; and evaluated using AUROC, AUPRC, F1, and Accuracy.",
            zh: "系统评估了 14 种编码器架构，包括 CNN、BiLSTM、mLSTM、xLSTM、Transformer、Linear Transformer、iTransformer、Mamba、RWKV、MAE，以及 DNABERT、DNABERT-2、NT、HyenaDNA 等 DNA LLM；设计了 6 种融合策略，包括拼接、相加、相减、逐元素乘法、双线性融合和拼接-差分-乘积融合，并使用 AUROC、AUPRC、F1 和 Accuracy 进行评估。",
          },
        ],
      },
      {
        titleEn: "Purdue University",
        titleZh: "普渡大学",
        meta: "Jan 2024 - Aug 2024",
        roleEn: "Research Assistant",
        roleZh: "研究助理",
        bullets: [
          {
            en: "Conducted mmWave radar research spanning image and point-cloud processing, pattern recognition, and image generation, with emphasis on model security for attack and defense.",
            zh: "开展了毫米波雷达研究，覆盖图像与点云处理、模式识别和图像生成，并重点关注模型安全中的攻击与防御问题。",
          },
          {
            en: "Performed signal analysis and window-function optimization on IWR6843, IWR1843, IWR1642, and Cascade EVM 2243x4 platforms, using FFT-based range, Doppler, and angle processing to extract point clouds and heatmaps.",
            zh: "在 IWR6843、IWR1843、IWR1642 和 Cascade EVM 2243x4 平台上完成信号分析与窗函数优化，利用基于 FFT 的距离、多普勒和角度处理提取点云与热力图。",
          },
          {
            en: "Developed and validated physical backdoor attacks against mmWave-based human activity recognition systems, advancing empirical understanding of sensing-system security vulnerabilities.",
            zh: "开发并验证了针对基于毫米波的人体活动识别系统的物理后门攻击，推进了对感知系统安全漏洞的实证理解。",
          },
        ],
      },
      {
        titleEn: "Purdue University",
        titleZh: "普渡大学",
        meta: "Aug 2024 - May 2025",
        roleEn: "Research Assistant",
        roleZh: "研究助理",
        bullets: [
          {
            en: "Conducted multimodal research across vision, audio, and text; studied deep learning security including backdoor attack implementation, defense, and adversarial robustness.",
            zh: "开展了视觉、音频和文本方向的多模态研究，并研究深度学习安全，包括后门攻击实现、防御和对抗鲁棒性。",
          },
          {
            en: "Fine-tuned and deployed large language models for downstream tasks, with emphasis on practical adaptation and robustness against adversarial attacks.",
            zh: "针对下游任务微调并部署了大语言模型，重点关注实际适配能力与对抗攻击下的鲁棒性。",
          },
        ],
      },
      {
        titleEn: "Purdue University",
        titleZh: "普渡大学",
        meta: "Jan 2021 - Jan 2024",
        roleEn: "Research Assistant",
        roleZh: "研究助理",
        bullets: [
          {
            en: "Conducted Alzheimer's research on relationships between age, education, MMSE, BMI, and brain fMRI connectivity across HCI, MCI, and AD stages; developed visualization software for high-dimensional medical data with arbitrary 2D projections and PCA traversal.",
            zh: "研究了年龄、受教育程度、MMSE、BMI 与 HCI、MCI、AD 不同阶段脑 fMRI 连接性的关系；并开发了支持任意二维投影与 PCA 遍历的高维医学数据可视化软件。",
          },
          {
            en: "Created animations for addictive-behavior analysis using nearest-neighbor, bilinear, bicubic, quintic, and affine Shepard interpolation to illustrate neurological changes.",
            zh: "使用最近邻、双线性、双三次、五次与仿射 Shepard 插值方法，为成瘾行为分析制作动画以展示神经学变化。",
          },
          {
            en: "Extracted and fine-tuned features with ResNet, EfficientNet, MobileNet, Xception, DenseNet, and CLIP (ViT) for medical imaging tasks.",
            zh: "在医学影像任务中使用 ResNet、EfficientNet、MobileNet、Xception、DenseNet 和 CLIP（ViT）进行特征提取与微调。",
          },
          {
            en: "Used NIH ABCD data to predict adolescent suicide risk and contributing factors, and applied machine learning to analyze the impact of COVID-19.",
            zh: "利用 NIH ABCD 数据预测青少年自杀风险及相关因素，并使用机器学习分析 COVID-19 的影响。",
          },
          {
            en: "Applied deep learning to discover iris-gene pattern links, used diffusion and Stable Diffusion models to generate irises for specific genotypes, and combined signal processing with deep learning for fine-grained mmWave action distinction and intention recognition under high similarity.",
            zh: "使用深度学习挖掘虹膜与基因模式之间的联系，利用扩散模型和 Stable Diffusion 为特定基因型生成虹膜图像，并结合信号处理与深度学习完成高相似场景下的细粒度毫米波动作区分与意图识别。",
          },
        ],
      },
    ],
    education: [
      {
        titleEn: "Indiana University Luddy School of Informatics, Computing, and Engineering",
        titleZh: "印第安纳大学 Luddy 信息、计算与工程学院",
        meta: "Aug 2025 - Present",
        roleEn: "Ph.D. Candidate, Computer Science (CS)",
        roleZh: "计算机科学博士候选人",
      },
      {
        titleEn: "Purdue University",
        titleZh: "普渡大学",
        meta: "Aug 2021 - May 2025",
        roleEn: "Ph.D. Candidate, Computer and Information Technology",
        roleZh: "计算与信息技术博士候选人",
        noteEn: "Transferred with advisor to Indiana University to continue doctoral study.",
        noteZh: "后随导师转入印第安纳大学继续博士阶段学习。",
      },
      {
        titleEn: "Purdue University",
        titleZh: "普渡大学",
        meta: "Aug 2019 - May 2021",
        roleEn: "M.S., Computer Science (CS)",
        roleZh: "计算机科学硕士",
      },
      {
        titleEn: "Beijing University of Technology",
        titleZh: "北京工业大学",
        meta: "Sep 2015 - May 2019",
        roleEn: "B.Eng., Electrical and Computer Engineering (ECE)",
        roleZh: "电子与计算机工程学士",
      },
    ],
  },
  projects: {
    ranked: [
      {
        name: "ClinicaLLM-OmniBench",
        url: "https://github.com/billzi2016/ClinicaLLM-OmniBench",
        language: "Python",
        updated: "2026-06-04",
        noteEn: "Most relevant benchmark-style repository for my current LLM / medical reasoning profile.",
        noteZh: "与我当前 LLM / 医学推理方向最相关的基准评测型仓库。",
      },
      {
        name: "ClinicaLLM-OmniBench-EN",
        url: "https://github.com/billzi2016/ClinicaLLM-OmniBench-EN",
        language: "Python",
        updated: "2026-06-04",
        noteEn: "English-facing companion version of the clinical LLM benchmark work.",
        noteZh: "临床 LLM 基准工作的英文版配套仓库。",
      },
      {
        name: "ai-agentic-arxiv-observer",
        url: "https://github.com/billzi2016/ai-agentic-arxiv-observer",
        language: "Python",
        updated: "2026-06-14",
        noteEn: "Agentic tooling around research monitoring, highly aligned with current AI automation work.",
        noteZh: "面向科研监控的智能体工具，与当前 AI 自动化方向高度契合。",
      },
      {
        name: "ReAct-AI-Agent",
        url: "https://github.com/billzi2016/ReAct-AI-Agent",
        language: "Python",
        updated: "2026-06-08",
        noteEn: "Full-stack ReAct AI algorithm solver with Django UI, streaming, Docker sandboxing, and TDD / CI-style loops.",
        noteZh: "全栈 ReAct AI 算法求解器，包含 Django 界面、流式输出、Docker 沙箱与 TDD / CI 风格闭环。",
      },
      {
        name: "AI-Agent",
        url: "https://github.com/billzi2016/AI-Agent",
        language: "Jupyter Notebook",
        updated: "2026-05-31",
        noteEn: "From-scratch AI coding agent course / notebook series, strongly aligned with my current agent-engineering direction.",
        noteZh: "从零实现 AI 编程智能体的课程 / 笔记系列，与我当前智能体工程方向高度一致。",
      },
      {
        name: "Pydantic-AI-Study",
        url: "https://github.com/billzi2016/Pydantic-AI-Study",
        language: "Python",
        updated: "2026-06-08",
        noteEn: "Focused study repo for agent runtime patterns and tool use.",
        noteZh: "聚焦智能体运行时模式与工具调用的研究仓库。",
      },
      {
        name: "build-from-scratch",
        url: "https://github.com/billzi2016/build-from-scratch",
        language: "Python",
        updated: "2026-06-14",
        noteEn: "Umbrella repo for educational implementations including tokenizer and vision-model reconstruction.",
        noteZh: "面向教学实现的总仓库，包含 tokenizer、视觉模型重构等内容。",
      },
      {
        name: "DeepChrInteract-v2",
        url: "https://github.com/billzi2016/DeepChrInteract-v2",
        language: "Python",
        updated: "2026-06-01",
        noteEn: "PyTorch reimplementation for enhancer-promoter interaction prediction with a wide encoder comparison space.",
        noteZh: "用于增强子-启动子互作预测的 PyTorch 重实现，覆盖大范围编码器比较实验。",
      },
      {
        name: "Apple-Silicon-LLM-Engine-from-Scratch",
        url: "https://github.com/billzi2016/Apple-Silicon-LLM-Engine-from-Scratch",
        language: "Python",
        updated: "2026-06-06",
        noteEn: "GPT-2 inference engine work spanning NumPy, PyTorch MPS, C++ / Metal, and KV cache ideas.",
        noteZh: "围绕 GPT-2 推理引擎的从零实现，涉及 NumPy、PyTorch MPS、C++ / Metal 和 KV cache 设计。",
      },
      {
        name: "Build-MCP-Step-by-Step",
        url: "https://github.com/billzi2016/Build-MCP-Step-by-Step",
        language: "Jupyter Notebook",
        updated: "2026-05-28",
        noteEn: "Structured build notes on MCP systems, relevant to tool integration and AI interoperability.",
        noteZh: "围绕 MCP 系统的结构化构建笔记，与工具集成和 AI 互操作高度相关。",
      },
      {
        name: "Build-DeepSeek-Step-by-Step",
        url: "https://github.com/billzi2016/Build-DeepSeek-Step-by-Step",
        language: "Jupyter Notebook",
        updated: "2026-05-31",
        noteEn: "Stepwise educational work around modern model systems and implementation details.",
        noteZh: "围绕现代模型系统与实现细节的分步骤教学型仓库。",
      },
      {
        name: "GPU-Test-and-Polite-Scheduler",
        url: "https://github.com/billzi2016/GPU-Test-and-Polite-Scheduler",
        language: "Python",
        updated: "2026-06-01",
        noteEn: "Useful systems repo for shared compute, scheduling, and GPU etiquette automation.",
        noteZh: "面向共享算力、任务调度与 GPU 使用规范自动化的系统型仓库。",
      },
      {
        name: "GPU-Test-and-Polite-Scheduler-EN",
        url: "https://github.com/billzi2016/GPU-Test-and-Polite-Scheduler-EN",
        language: "Python",
        updated: "2026-06-01",
        noteEn: "English-facing version of the same scheduler work.",
        noteZh: "同一调度项目的英文版仓库。",
      },
      {
        name: "midi-react-ai-agent-search",
        url: "https://github.com/billzi2016/midi-react-ai-agent-search",
        language: "Python",
        updated: "2026-06-10",
        noteEn: "ReAct-style natural-language search over a very large MIDI corpus.",
        noteZh: "面向超大 MIDI 语料的 ReAct 风格自然语言搜索系统。",
      },
      {
        name: "LLM-Gap-Tracker",
        url: "https://github.com/billzi2016/LLM-Gap-Tracker",
        language: "Python",
        updated: "2026-05-30",
        noteEn: "Tracking-oriented repository around LLM model differences and progress gaps.",
        noteZh: "围绕 LLM 模型差异与进展缺口跟踪的仓库。",
      },
      {
        name: "gpt-oss",
        url: "https://github.com/billzi2016/gpt-oss",
        language: "Python",
        updated: "2026-05-27",
        noteEn: "Repository related to OpenAI open-weight model usage and experimentation.",
        noteZh: "与 OpenAI 开源权重模型使用和实验相关的仓库。",
      },
      {
        name: "DeepChrInteract",
        url: "https://github.com/billzi2016/DeepChrInteract",
        language: "Python",
        updated: "2026-06-01",
        noteEn: "Foundational reference repo tied directly to my biomedical sequence modeling work.",
        noteZh: "与我生物医学序列建模工作直接相关的基础参考仓库。",
      },
      {
        name: "Megatron-LM",
        url: "https://github.com/billzi2016/Megatron-LM",
        language: "Python",
        updated: "2026-06-04",
        noteEn: "Training-at-scale exploration repository, relevant to large-model systems interests.",
        noteZh: "面向大模型系统训练扩展的探索仓库。",
      },
      {
        name: "foundation-model-analysis",
        url: "https://github.com/billzi2016/foundation-model-analysis",
        language: "Jupyter Notebook",
        updated: "2026-05-27",
        noteEn: "Analysis-oriented repository around contemporary foundation models.",
        noteZh: "围绕当代基础模型的分析型仓库。",
      },
      {
        name: "ai-agent-practice-playbook",
        url: "https://github.com/billzi2016/ai-agent-practice-playbook",
        language: "Jupyter Notebook",
        updated: "2026-05-17",
        noteEn: "Supporting notes and experiments around practical agent construction.",
        noteZh: "围绕实用型智能体构建的笔记与实验仓库。",
      },
    ],
    all: [
      { name: "ai-agentic-arxiv-observer", url: "https://github.com/billzi2016/ai-agentic-arxiv-observer", language: "Python" },
      { name: "build-from-scratch", url: "https://github.com/billzi2016/build-from-scratch", language: "Python" },
      { name: "Study", url: "https://github.com/billzi2016/Study", language: "none" },
      { name: "midi-react-ai-agent-search", url: "https://github.com/billzi2016/midi-react-ai-agent-search", language: "Python", noteEn: "MIDI search tool with ReAct AI agent.", noteZh: "带 ReAct AI 智能体的 MIDI 搜索工具。" },
      { name: "Pydantic-AI-Study", url: "https://github.com/billzi2016/Pydantic-AI-Study", language: "Python" },
      { name: "vlm-hybrid-gallery", url: "https://github.com/billzi2016/vlm-hybrid-gallery", language: "Python" },
      { name: "ReAct-AI-Agent", url: "https://github.com/billzi2016/ReAct-AI-Agent", language: "Python", noteEn: "Full-stack ReAct AI algorithm solver with Django UI and Docker sandbox.", noteZh: "带 Django 界面和 Docker 沙箱的全栈 ReAct AI 算法求解器。" },
      { name: "ATmega2560-Graphical-RPN-Scientific-Calculator", url: "https://github.com/billzi2016/ATmega2560-Graphical-RPN-Scientific-Calculator", language: "C++" },
      { name: "ATMega328p-RPN-Scientific-Calculator", url: "https://github.com/billzi2016/ATMega328p-RPN-Scientific-Calculator", language: "C++" },
      { name: "ATmega2560-LCD12864-Game-Of-Life", url: "https://github.com/billzi2016/ATmega2560-LCD12864-Game-Of-Life", language: "C++" },
      { name: "Homemade-Tiny-OS", url: "https://github.com/billzi2016/Homemade-Tiny-OS", language: "Python", noteEn: "User-space micro operating-system simulator with virtual disk, file system, process scheduling, and shell.", noteZh: "带虚拟磁盘、文件系统、进程调度与 shell 的用户态微型操作系统模拟器。" },
      { name: "bignum-from-scratch", url: "https://github.com/billzi2016/bignum-from-scratch", language: "Python", noteEn: "Arbitrary-precision BigInt and BigFloat implementation from scratch.", noteZh: "从零实现任意精度 BigInt 与 BigFloat。" },
      { name: "Homemade-CPython", url: "https://github.com/billzi2016/Homemade-CPython", language: "Python" },
      { name: "Apple-Silicon-LLM-Engine-from-Scratch", url: "https://github.com/billzi2016/Apple-Silicon-LLM-Engine-from-Scratch", language: "Python", noteEn: "GPT-2 inference engine from scratch for Apple Silicon.", noteZh: "面向 Apple Silicon 的 GPT-2 推理引擎从零实现。" },
      { name: "Reverse-Polish-Notation-Calculator", url: "https://github.com/billzi2016/Reverse-Polish-Notation-Calculator", language: "Python", noteEn: "RPN scientific calculator with AST visualization.", noteZh: "带 AST 可视化的逆波兰科学计算器。" },
      { name: "Apple-Silicon-Profiler", url: "https://github.com/billzi2016/Apple-Silicon-Profiler", language: "Python" },
      { name: "Visual-Basic-Core-Compiler", url: "https://github.com/billzi2016/Visual-Basic-Core-Compiler", language: "Python" },
      { name: "Self-Hosting-C-Core-Compiler", url: "https://github.com/billzi2016/Self-Hosting-C-Core-Compiler", language: "C", noteEn: "Self-hosting C core compiler.", noteZh: "可自举的 C 核心编译器。" },
      { name: "SDD-Industry-Standard", url: "https://github.com/billzi2016/SDD-Industry-Standard", language: "none", noteEn: "Specification-driven development notes and methodology.", noteZh: "规格驱动开发的方法论与文档仓库。" },
      { name: "label-studio", url: "https://github.com/billzi2016/label-studio", language: "TypeScript", noteEn: "Multi-type data labeling and annotation tool.", noteZh: "多类型数据标注工具。" },
      { name: "C-Core-Compiler", url: "https://github.com/billzi2016/C-Core-Compiler", language: "Python" },
      { name: "chaos-algorithms", url: "https://github.com/billzi2016/chaos-algorithms", language: "JavaScript" },
      { name: "cordic-fixedpoint-algorithm", url: "https://github.com/billzi2016/cordic-fixedpoint-algorithm", language: "Python" },
      { name: "Autograd-Compiler-Engine", url: "https://github.com/billzi2016/Autograd-Compiler-Engine", language: "Python" },
      { name: "Automatic-Differentiation-From-Scratch", url: "https://github.com/billzi2016/Automatic-Differentiation-From-Scratch", language: "Python" },
      { name: "ClinicaLLM-OmniBench-EN", url: "https://github.com/billzi2016/ClinicaLLM-OmniBench-EN", language: "Python" },
      { name: "ClinicaLLM-OmniBench", url: "https://github.com/billzi2016/ClinicaLLM-OmniBench", language: "Python" },
      { name: "Smart-Huffman-Archiver", url: "https://github.com/billzi2016/Smart-Huffman-Archiver", language: "Python" },
      { name: "Megatron-LM", url: "https://github.com/billzi2016/Megatron-LM", language: "Python", noteEn: "Ongoing research training transformer models at scale.", noteZh: "面向大规模 Transformer 训练的持续研究仓库。" },
      { name: "DTMF-Encod-Decode", url: "https://github.com/billzi2016/DTMF-Encod-Decode", language: "Python" },
      { name: "backup-utils", url: "https://github.com/billzi2016/backup-utils", language: "Python", noteEn: "Robust exFAT to APFS backup scripts.", noteZh: "稳健的 exFAT 到 APFS 备份脚本。" },
      { name: "Arduino-Wired-Telegraph", url: "https://github.com/billzi2016/Arduino-Wired-Telegraph", language: "C++" },
      { name: "RS485-Modbus-Concrete-Sensor-Monitor", url: "https://github.com/billzi2016/RS485-Modbus-Concrete-Sensor-Monitor", language: "Python", noteEn: "Real-time sensor monitoring system with Django and Redis.", noteZh: "基于 Django 和 Redis 的实时传感器监测系统。" },
      { name: "Custom-Style-AI-Chat", url: "https://github.com/billzi2016/Custom-Style-AI-Chat", language: "Python" },
      { name: "Prime-Sieve-Algorithms", url: "https://github.com/billzi2016/Prime-Sieve-Algorithms", language: "Python" },
      { name: "z3", url: "https://github.com/billzi2016/z3", language: "C++", noteEn: "The Z3 theorem prover.", noteZh: "Z3 定理证明器。" },
      { name: "Four-Color-Theorem", url: "https://github.com/billzi2016/Four-Color-Theorem", language: "Python" },
      { name: "LCD12864-Dither-TV", url: "https://github.com/billzi2016/LCD12864-Dither-TV", language: "Python" },
      { name: "LCD12864-Bad-Apple", url: "https://github.com/billzi2016/LCD12864-Bad-Apple", language: "Python" },
      { name: "python-tetris-ai", url: "https://github.com/billzi2016/python-tetris-ai", language: "Python" },
      { name: "Alphago-Naive", url: "https://github.com/billzi2016/Alphago-Naive", language: "Python" },
      { name: "GPU-Test-and-Polite-Scheduler-EN", url: "https://github.com/billzi2016/GPU-Test-and-Polite-Scheduler-EN", language: "Python" },
      { name: "GPU-Test-and-Polite-Scheduler", url: "https://github.com/billzi2016/GPU-Test-and-Polite-Scheduler", language: "Python" },
      { name: "RomeInADay", url: "https://github.com/billzi2016/RomeInADay", language: "HTML" },
      { name: "Alphafold-V2-Reproduction", url: "https://github.com/billzi2016/Alphafold-V2-Reproduction", language: "Python" },
      { name: "Alphafold-V1-Reproduction", url: "https://github.com/billzi2016/Alphafold-V1-Reproduction", language: "Python" },
      { name: "DeepChrInteract-v2", url: "https://github.com/billzi2016/DeepChrInteract-v2", language: "Python", noteEn: "EPI prediction with 14 encoder architectures.", noteZh: "包含 14 类编码器架构的 EPI 预测仓库。" },
      { name: "Build-DeepSeek-Step-by-Step", url: "https://github.com/billzi2016/Build-DeepSeek-Step-by-Step", language: "Jupyter Notebook" },
      { name: "AI-Agent", url: "https://github.com/billzi2016/AI-Agent", language: "Jupyter Notebook", noteEn: "From-scratch AI coding agent course.", noteZh: "从零实现 AI 编程智能体课程。" },
      { name: "Metropolitan-Routing-Algorithm", url: "https://github.com/billzi2016/Metropolitan-Routing-Algorithm", language: "Python" },
      { name: "LLM-Gap-Tracker", url: "https://github.com/billzi2016/LLM-Gap-Tracker", language: "Python" },
      { name: "ESP32-Prometheus-PC-Monitor", url: "https://github.com/billzi2016/ESP32-Prometheus-PC-Monitor", language: "C++" },
      { name: "ESP8266-Token-Counter", url: "https://github.com/billzi2016/ESP8266-Token-Counter", language: "C++" },
      { name: "ESP8266-Codex-Usage-Monitor", url: "https://github.com/billzi2016/ESP8266-Codex-Usage-Monitor", language: "C++" },
      { name: "SQLite-Chaos-Tester", url: "https://github.com/billzi2016/SQLite-Chaos-Tester", language: "Python" },
      { name: "speckit", url: "https://github.com/billzi2016/speckit", language: "Jupyter Notebook" },
      { name: "ViT-H", url: "https://github.com/billzi2016/ViT-H", language: "Python", noteEn: "ViT-H/14 training on CIFAR-10 with Flash Attention and bf16.", noteZh: "在 CIFAR-10 上使用 Flash Attention 与 bf16 训练 ViT-H/14。" },
      { name: "system-burner", url: "https://github.com/billzi2016/system-burner", language: "Python" },
      { name: "Build-MCP-Step-by-Step", url: "https://github.com/billzi2016/Build-MCP-Step-by-Step", language: "Jupyter Notebook" },
      { name: "Daily-Leetcode", url: "https://github.com/billzi2016/Daily-Leetcode", language: "Python" },
      { name: "Whisper", url: "https://github.com/billzi2016/Whisper", language: "Python" },
      { name: "system-design-interview", url: "https://github.com/billzi2016/system-design-interview", language: "Python" },
      { name: "MCU-Design-and-Prototypes-Sandbox", url: "https://github.com/billzi2016/MCU-Design-and-Prototypes-Sandbox", language: "Jupyter Notebook" },
      { name: "foundation-model-analysis", url: "https://github.com/billzi2016/foundation-model-analysis", language: "Jupyter Notebook" },
      { name: "LLM-AI-Papers", url: "https://github.com/billzi2016/LLM-AI-Papers", language: "Python" },
      { name: "codex-config", url: "https://github.com/billzi2016/codex-config", language: "Python" },
      { name: "http-server-from--scratch", url: "https://github.com/billzi2016/http-server-from--scratch", language: "Jupyter Notebook" },
      { name: "ESP32-Weather-Box", url: "https://github.com/billzi2016/ESP32-Weather-Box", language: "Python" },
      { name: "MRI_Deep_Learning_Projects", url: "https://github.com/billzi2016/MRI_Deep_Learning_Projects", language: "Python" },
      { name: "Heuristic-Algorithm", url: "https://github.com/billzi2016/Heuristic-Algorithm", language: "Jupyter Notebook" },
      { name: "openai-gym-reinforcement-learning-lab", url: "https://github.com/billzi2016/openai-gym-reinforcement-learning-lab", language: "Jupyter Notebook" },
      { name: "inverted-pendulum-rl-lab", url: "https://github.com/billzi2016/inverted-pendulum-rl-lab", language: "Jupyter Notebook", noteEn: "Inverted pendulum RL lab with DQN, PPO, DDPG, and SAC.", noteZh: "包含 DQN、PPO、DDPG 与 SAC 的倒立摆强化学习实验室。" },
      { name: "leetcode-terminator", url: "https://github.com/billzi2016/leetcode-terminator", language: "Python", noteEn: "Local AI-assisted LeetCode tool using Ollama.", noteZh: "基于 Ollama 的本地 AI 辅助 LeetCode 工具。" },
      { name: "Make-GitHub-Green-Again-Time-Machine-via-Local-AI-Agent-Ollama-VLLM-LangChain", url: "https://github.com/billzi2016/Make-GitHub-Green-Again-Time-Machine-via-Local-AI-Agent-Ollama-VLLM-LangChain", language: "Python" },
      { name: "Daily-Paper-Reading", url: "https://github.com/billzi2016/Daily-Paper-Reading", language: "Python" },
      { name: "RL-MCTS-gomoku-zero-11x11", url: "https://github.com/billzi2016/RL-MCTS-gomoku-zero-11x11", language: "Python" },
      { name: "django-with-speckit", url: "https://github.com/billzi2016/django-with-speckit", language: "Python", noteEn: "Django with speckit.", noteZh: "结合 speckit 的 Django 项目。" },
      { name: "ai-agent-reflection", url: "https://github.com/billzi2016/ai-agent-reflection", language: "none" },
      { name: "gomoku-minimax-engine", url: "https://github.com/billzi2016/gomoku-minimax-engine", language: "Shell" },
      { name: "MIMO-FMCW-Radar-Simulator-Multiprocess", url: "https://github.com/billzi2016/MIMO-FMCW-Radar-Simulator-Multiprocess", language: "Python" },
      { name: "automl-autodl", url: "https://github.com/billzi2016/automl-autodl", language: "Python" },
      { name: "mmwave-fmcw-cascade-mimo-sensing-platform", url: "https://github.com/billzi2016/mmwave-fmcw-cascade-mimo-sensing-platform", language: "Python" },
      { name: "intelligent-esp32-drone-racing-gate-system", url: "https://github.com/billzi2016/intelligent-esp32-drone-racing-gate-system", language: "C++" },
      { name: "immersive-vr-xr-security-telemetry-platform", url: "https://github.com/billzi2016/immersive-vr-xr-security-telemetry-platform", language: "Jupyter Notebook" },
      { name: "ai-agent-practice-playbook", url: "https://github.com/billzi2016/ai-agent-practice-playbook", language: "Jupyter Notebook" },
      { name: "mmlock-fmcw-radar-deep-security", url: "https://github.com/billzi2016/mmlock-fmcw-radar-deep-security", language: "Jupyter Notebook" },
      { name: "advanced-sorting-algorithms", url: "https://github.com/billzi2016/advanced-sorting-algorithms", language: "Python" },
      { name: "advanced-search-data-structures", url: "https://github.com/billzi2016/advanced-search-data-structures", language: "Python" },
      { name: "llm-auto-rag-survey", url: "https://github.com/billzi2016/llm-auto-rag-survey", language: "Python" },
      { name: "real-time-yolo-vision-intelligence-lab", url: "https://github.com/billzi2016/real-time-yolo-vision-intelligence-lab", language: "Jupyter Notebook" },
      { name: "gpt-oss", url: "https://github.com/billzi2016/gpt-oss", language: "Python", noteEn: "Open-weight language model experiments.", noteZh: "开源权重语言模型实验仓库。" },
      { name: "AI-Chat", url: "https://github.com/billzi2016/AI-Chat", language: "HTML" },
      { name: "DeepChrInteract", url: "https://github.com/billzi2016/DeepChrInteract", language: "Python", noteEn: "Instructions for use of this project.", noteZh: "该项目的使用说明仓库。" },
    ],
  },
};
